name: GHA Triggers BK Builds
run-name: ${{ github.actor }} is testing out GitHub Actions triggering BK ğŸš€
on: [push]
jobs:
  Trigger-BK:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.2.0"
